Fix some bugs
InnoD-WebTier/calwtcrew pull request #15
Opened 2017-05-01 16:24 UTC by cindytung

- fix a section headers bug where all of them turned blue on hover, instead of just the schedule section headers
- disabled text select on schedule section headers
- change about me link to about

2017-05-01 16:34 UTC, jubearsun requested changes

2017-05-01 16:34 UTC, jubearsun commented on css/schedule.scss
>    &:hover {
can you make this cursor: pointer on hover? and have some transition (maybe 250ms)

2017-05-01 17:25 UTC, cindytung commented on css/schedule.scss
>    &:hover {
im using display:none to hide the result info on toggle, but is there a way to have add transition to display properties? or do i need to use max-height?

2017-05-01 17:29 UTC, jubearsun commented on css/schedule.scss
>    &:hover {
Ah got it, you can't do transition on display but you can set opacity and height to 0 and keep display block

2017-05-01 22:49 UTC, cindytung commented on css/schedule.scss
>    &:hover {
i fixed it but it actually looks a bit weird hmm

2017-05-02 04:39 UTC, jubearsun requested changes

2017-05-02 04:39 UTC, jubearsun commented on css/schedule.scss
> +      transition: max-height 2s;
2s is too long, can you change it to 250ms

2017-05-04 04:54 UTC, cindytung commented
SRY FOR THE LATE CHANGES HAHA

2017-05-04 05:33 UTC, merged