not done yet :(
InnoD-WebTier/calwtcrew pull request #4
Opened 2017-04-11 00:43 UTC by cindytung

2017-04-11 01:49 UTC, jubearsun requested changes

2017-04-11 01:49 UTC, jubearsun commented on components/Officers.js
> +      {this.people.map((data) => {
nit: You can do arrow return
```js
this.people.map((data) => (
  <Photo data={people} key={data.name} />
));
```

2017-04-11 01:49 UTC, jubearsun commented on components/photo.js
> +const Photo = (props) => (
`class Photo extends React.Component`

2017-04-19 20:26 UTC, cindytung commented on components/photo.js
> +const Photo = (props) => (
changed impl for Photo to stateless, so don't need to extend React.Component anymore

2017-04-19 20:29 UTC, jubearsun requested changes

2017-04-19 20:29 UTC, jubearsun commented on css/aboutme.scss
> +body {
Remove this line if there are no styles in it

2017-04-19 20:29 UTC, jubearsun commented on css/aboutme.scss
> +#team {
The indents in this file are off, can you double check that they're 2 space indents?

2017-04-19 20:29 UTC, jubearsun commented on css/aboutme.scss
> +    margin-bottom: 2%;
Please fix indentation here and elsewhere

2017-04-19 20:29 UTC, jubearsun commented on css/base.scss
> +	text-align: center;
Please fix indentation here and elsewhere.

2017-04-19 20:29 UTC, jubearsun commented on pages/about.js
> +// import { Link } from 'react-router';
Remove this comment if unused

2017-04-19 21:49 UTC, merged